---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/malefemale/malefemale.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/190631/master/file/figures/malefemale/malefemale.csv"
    folder_url: "/users/2191/articles/190631/master/folder/figures/malefemale"
    treatFirstLineAsHeader: true
